//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by wmdmapp.rc
//
#define IDOK2                           2
#define IDI_ICON                        101
#define IDS_APP_TITLE                   102
#define IDR_MENU                        139
#define IDD_DEVICES                     140
#define IDD_DEVICEFILES                 141
#define IDI_DEVICE                      143
#define IDD_PROGRESS                    144
#define IDD_WORKING                     145
#define IDD_PROPERTIES_DEVICE           146
#define IDD_PROPERTIES_SIMPLESTORAGE    147
#define IDD_PROPERTIES_ALBUMSTORAGE     148
#define IDR_CONTEXT_MENU                149
#define ID_OPTIONS_USEINSERT3           150
#define IDD_PLAYLIST_NAME               151
#define IDD_ENTER_ALBUMINFO             152
#define IDD_ENTER_MEDIACASTINFO         153
#define IDS_REG_ROOT                    201
#define IDS_REG_PATH_BASE               202
#define IDS_REG_KEY_XPOS                251
#define IDS_REG_KEY_YPOS                252
#define IDS_REG_KEY_WIDTH               253
#define IDS_REG_KEY_HEIGHT              254
#define IDS_DEF_WIDTH                   301
#define IDS_DEF_HEIGHT                  302
#define IDS_COLSIZE_1                   501
#define IDS_COLSIZE_2                   502
#define IDS_COLSIZE_3                   503
#define IDS_COLSIZE_4                   504
#define IDS_COLSIZE_5                   505
#define IDS_COLSIZE_6                   506
#define IDS_COLSIZE_7                   507
#define IDS_COLNAME_1                   551
#define IDS_COLNAME_2                   552
#define IDS_COLNAME_3                   553
#define IDS_COLNAME_4                   554
#define IDS_COLNAME_5                   555
#define IDS_COLNAME_6                   556
#define IDS_COLNAME_7                   557
#define IDS_COLNAME_8                   558
#define IDS_SB_DEVICE_ONE               701
#define IDS_SB_DEVICE_MANY              702
#define IDS_SB_DEVICEFILES_ONE          703
#define IDS_SB_DEVICEFILES_MANY         704
#define IDS_SB_DEVICEFILES_FREE         705
#define IDS_SB_DEVICEFILES_USED         706
#define IDS_STATUS_EMPTY                707
#define IDS_PROGRESS_COUNT              708
#define IDS_PROGRESS_BYTECOUNT          709
#define IDS_BYTESSIZE_NOCOMMA           801
#define IDS_KBSIZE_NOCOMMA              802
#define IDS_KBSIZE_COMMA                803
#define IDS_MBSIZE_NOCOMMA              804
#define IDS_MBSIZE_COMMA                805
#define IDS_MBSIZE_DECIMAL              806
#define IDS_REVOKED_CAPTION             900
#define IDS_APP_UPDATE_URL              901
#define IDS_APP_REVOKED                 902
#define IDS_COMPONENT_REVOKED           903
#define IDS_PROPERTIES_CAPTION          904
#define IDC_LV_DEVICEFILES              1007
#define IDC_LV_DEVICES                  1008
#define IDC_PB_PROGRESS                 1009
#define IDC_ST_OPERATION                1010
#define IDC_ST_DETAILS                  1011
#define IDC_ST_COUNTER                  1012
#define IDC_ST_BYTECOUNTER              1013
#define IDC_SERIALID                    1014
#define IDC_SERIALID_STRING             1015
#define IDC_MANUFACTURER                1016
#define IDC_DEVICE_TYPE                 1017
#define IDC_ATTRIBUTES                  1018
#define IDC_POWER_CAP                   1018
#define IDC_CAPABILITIES                1019
#define IDC_POWER_IS                    1019
#define IDC_PLAYLIST                    1020
#define IDC_ALBUMFORMAT                 1021
#define IDC_ALBUMSIZE                   1022
#define IDC_ALBUMDURATION               1023
#define IDC_ALBUMWIDTH                  1024
#define IDC_FORMAT                      1025
#define IDC_PLAYLIST_NAME               1026
#define IDC_ALBUMHEIGHT                 1026
#define IDC_REFERENCES                  1027
#define IDC_VERSION                     1028
#define IDC_REFERENCES2                 1028
#define IDC_ALBUMACTUALWIDTH            1028
#define IDC_DEVICE_STATUS               1029
#define IDC_ALBUM_NAME                  1030
#define IDC_DEVICE_STATUS2              1031
#define IDC_ALBUMACTUALHEIGHT           1032
#define IDC_VENDOR_EXT_DESC             1033
#define IDC_ALBUMIMAGE_FILEPATH         1034
#define IDC_ALBUMIMAGE                  1035
#define IDC_ALBUM_FORMATCODE            1036
#define IDC_BROWSE                      1037
#define IDC_DEVICE_PROTOCOL             1038
#define IDC_SP_VENDOR                   1039
#define IDC_MEDIACAST_NAME              1040
#define IDC_OWNER                       1041
#define IDC_SOURCE_URL                  1042
#define IDC_SUMMARY                     1043
#define IDC_OBJECT_BOOKMARK             1047
#define IDC_PODCAST_PATH                1048
#define IDC_EDITOR                      1049
#define IDC_WEBMASTER                   1050
#define IDC_DESTINATION_URL             1051
#define IDC_CATEGORY                    1052
#define IDC_MODELNAME                   1053
#define IDC_FIRMWAREVER                 1054
#define IDM_DELETE                      32777
#define IDM_DEVICE_RESET                32783
#define IDM_CLOSE                       32784
#define IDM_REFRESH                     32785
#define IDM_OPTIONS_USE_OPERATION_INTERFACE 32786
#define IDM_PROPERTIES                  32787
#define ID_OPTIONS_USEENUMDEVICES2      32788
#define IDM_CREATEPLAYLIST              32789
#define IDM_CREATEALBUM                 32790
#define IDM_CREATEMEDIACAST             32791
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        154
#define _APS_NEXT_COMMAND_VALUE         32791
#define _APS_NEXT_CONTROL_VALUE         1041
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
